# Generated by Django 2.2.16 on 2020-10-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='pol',
        ),
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='students',
            name='interests',
            field=models.TextField(default='None'),
        ),
    ]
